backend/models/Apple.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "apple".
 *
 * @property int $id
 * @property string $color
 * @property int $created_at
 * @property int $fell_at
 * @property int $status
 * @property float $size
 * @property float $spoiled
 */
class Apple extends \yii\db\ActiveRecord
{
    const STATUS_ON_THE_TREE = 1;
    const STATUS_ON_THE_GROUND = 2;
    const STATUS_ROTTEN = 3;
    public static $statuses = [
        self::STATUS_ON_THE_TREE => 'On the tree',
        self::STATUS_ON_THE_GROUND => 'On the ground',
        self::STATUS_ROTTEN => 'Rotten',
    ];

    public static $colors = [
        'black','green','yellow','red'
    ];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'apple';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['color', 'created_at'], 'required'],
            [['created_at', 'fell_at', 'status'], 'integer'],
            [['size', 'spoiled'], 'double'],
            [['color'], 'string', 'max' => 100],
        ];
    }

    public function eat($percent){
        $percent = (float)$percent / 100;
        $size = $this->size - $this->spoiled;
        if ($this->status != self::STATUS_ON_THE_GROUND){
            return 'The apple is not in the ground or not fresh';
        }elseif($percent < 0 || $percent > 1){
            return 'Percent incorrect';
        }elseif($percent > $size){
            return 'No so much edible and fresh apple';
        }else{
            $this->size -= $percent;
            return true;
        }
    }
    public function fall(){
        if($this->status == self::STATUS_ON_THE_TREE){
            $this->status = self::STATUS_ON_THE_GROUND;
            $this->fell_at = time();
            $this->save(false);
        }
    }
    public function beforeSave($insert)
    {
        if ($insert){
            if(!$this->color){
                $this->color = self::$colors[rand(0, count(self::$colors) - 1)];
            }
            if(!$this->created_at){
                $this->created_at = rand(strtotime('-1 year'), time());
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'color' => 'Color',
            'created_at' => 'Created At',
            'fell_at' => 'Fell At',
            'status' => 'Status',
            'size' => 'Size',
            'spoiled' => 'Spoiled',
        ];
    }
}

backend/controllers/AppleController.php
<?php

namespace backend\controllers;

use Throwable;
use Yii;
use backend\models\Apple;
use backend\models\AppleSearch;
use yii\db\StaleObjectException;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * AppleController implements the CRUD actions for Apple model.
 */
class AppleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Apple models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AppleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Apple model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Apple model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        for ($i = 1; $i <= rand(1, 10); $i++){
            $model = new Apple();
            $model->save(false);
        }
        Yii::$app->session->setFlash('success','Apples added successfully');
        return $this->redirect('index');
    }

    /**
     * Updates an existing Apple model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionEat(){
        if(Yii::$app->request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            $id = Yii::$app->request->post('id');
            $model = $this->findModel($id);
            $success = $model->eat(Yii::$app->request->post('percent'));
            if($success === true){
                $model->save();
                return ['error'=>0];
            }else{
                return ['error'=>1, 'message'=>$success];
            }
        }else{
            return $this->redirect('index');
        }
    }
    /**
     * Deletes an existing Apple model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionFall($id)
    {
        $this->findModel($id)->fall();
        Yii::$app->session->setFlash('success','The apple successfully fell to the ground');
        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Apple model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Apple model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Apple the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Apple::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/apple/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Apple */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="apple-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'color')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'fell_at')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'size')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'spoiled')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/apple/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\AppleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="apple-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'color') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'fell_at') ?>

    <?= $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'size') ?>

    <?php // echo $form->field($model, 'spoiled') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/apple/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Apple */

$this->title = 'Create Apple';
$this->params['breadcrumbs'][] = ['label' => 'Apples', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="apple-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/apple/index.php
<?php

use backend\models\Apple;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\AppleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Apples';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="apple-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Generate apples', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'id'=>'apple-grid',
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'color',
            'created_at:datetime',
            'fell_at:datetime',
            [
                'attribute'=>'status',
                'value'=>function($model){
                    $statuses = Apple::$statuses;
                    return $statuses[$model->status];
                },
                'filter'=> Apple::$statuses,
            ],
            'size',
            'spoiled',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{fall} {eat}',

                'buttons'=>[
                    'fall'=>function($url, $model, $key) {
                        if($model->status == Apple::STATUS_ON_THE_TREE){
                            return Html::a('Fall to ground', ['apple/fall', 'id'=>$model->id]);
                        }
                    },
                    'eat'=>function($url, $model, $key) {
                        if($model->status == Apple::STATUS_ON_THE_GROUND && $model->size > 0){
                            return Html::input('number','eat', '', ['class'=>'form-control','placeholder'=>'Eat (percent %)', 'id'=>'eat_'.$model->id]).
                                ''.Html::button('Eat', ['id'=>'btn_eat_'.$model->id, 'data-id'=>$model->id,'class'=>'btn btn-primary btn-sm eat_btn']);
                        }
                    },
                ],
            ]
        ],
    ]);
    $url = Yii::$app->urlManager->createUrl('apple/eat');
    $js = <<<JS
        $(document).on('click', '.eat_btn', function() {
            var id = $(this).data('id');
            $.ajax({
                url: '{$url}',
                method: 'post',
                data: {
                    id: id,
                    percent: $('#eat_'+id).val()
                },
                dataType: 'json',
                error: function(a,b,c) {
                    console.log('Error', a,b,c);
                },
                'success': function(data) {
                    if(data['error'] == 1){
                        alert(data['message'])
                    }else{
                        window.location = window.location;
                    }
                }
            });
        });
JS;
    $this->registerJs($js);
?>
</div>

backend/views/apple/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Apple */

$this->title = 'Update Apple: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Apples', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="apple-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/apple/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Apple */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Apples', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="apple-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'color',
            'created_at',
            'fell_at',
            'status',
            'size',
            'spoiled',
        ],
    ]) ?>

</div>